#!/usr/bin/env python3
"""Deterministic helper for the LLM Wiki in this vault.

Uses only the Python standard library (Python 3.8 or newer).

Run from the vault folder:

    python3 scripts/wiki_tool.py <command>      # macOS / Linux
    python scripts/wiki_tool.py <command>       # Windows (or: py scripts/wiki_tool.py)

Commands: doctor, build, lint, source-scan, source-lint, source-delta,
source-coverage, search-catalog, log. See Schema/command-reference.md.
"""

import argparse
import datetime
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WIKI = ROOT / "Wiki"
RAW_SOURCES = ROOT / "Raw" / "Sources"
CATALOG = WIKI / "catalog.jsonl"
INDEX = WIKI / "index.md"
LOG = WIKI / "log.md"
MANIFEST = ROOT / "Schema" / "source-manifest.jsonl"

# Folder under Wiki/ -> the one tag its notes must carry.
WIKI_FOLDERS = {
    "Topics": "topic",
    "Concepts": "concept",
    "Entities": "entity",
    "Projects": "project",
    "Logs": "log",
}
ALLOWED_TAGS = set(WIKI_FOLDERS.values())
ALLOWED_STATUS = {"seed", "growing", "evergreen"}
WIKI_REQUIRED = ["tags", "status", "created", "updated", "sources", "source_count"]
SOURCE_REQUIRED = ["Title", "Reference", "Created", "Processed", "tags"]
REQUIRED_DIRS = [
    "Raw/Sources",
    "Raw/Files",
    "Wiki",
    *("Wiki/" + name for name in WIKI_FOLDERS),
    "Schema",
    "_templates",
    ".agents/skills",
    "scripts",
]
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
GENERATED_NOTICE = "Generated by `scripts/wiki_tool.py build`. Do not edit by hand."


# ---------------------------------------------------------------- helpers


def rel(path):
    """Vault-relative path with forward slashes, the same on every OS."""
    return path.relative_to(ROOT).as_posix()


def today():
    return datetime.date.today().isoformat()


def read_text(path):
    return path.read_text(encoding="utf-8")


def write_text(path, text):
    """Write UTF-8 with \\n line endings so files do not churn between OSes."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def parse_scalar(value):
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    if value.lower() == "true":
        return True
    if value.lower() == "false":
        return False
    if re.fullmatch(r"-?\d+", value):
        return int(value)
    return value


def split_inline_list(inner):
    """Split the inside of [a, "b, c", [[link]]] on top-level commas."""
    items, current, quote, depth = [], "", None, 0
    for char in inner:
        if quote:
            current += char
            if char == quote:
                quote = None
        elif char in "\"'":
            quote = char
            current += char
        elif char == "[":
            depth += 1
            current += char
        elif char == "]":
            depth -= 1
            current += char
        elif char == "," and depth == 0:
            items.append(current)
            current = ""
        else:
            current += char
    if current.strip():
        items.append(current)
    return [parse_scalar(item) for item in items if item.strip()]


def parse_frontmatter(text):
    """Parse the small YAML subset these notes use.

    Returns (fields, body). fields is None when the note has no frontmatter.
    Supports `key: value`, `key: []`, `key: [a, b]` and block lists (`  - item`).
    """
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None, text
    end = None
    for number, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            end = number
            break
    if end is None:
        return None, text
    fields, key = {}, None
    for line in lines[1:end]:
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        item = re.match(r"^\s+-\s*(.*)$", line)
        if item and key is not None:
            if not isinstance(fields[key], list):
                fields[key] = []
            fields[key].append(parse_scalar(item.group(1)))
            continue
        pair = re.match(r"^([^\s:][^:]*):\s*(.*)$", line)
        if not pair:
            continue
        key, value = pair.group(1).strip(), pair.group(2).strip()
        if value == "":
            fields[key] = ""
        elif value.startswith("[") and value.endswith("]") and not value.startswith("[["):
            fields[key] = split_inline_list(value[1:-1])
        else:
            fields[key] = parse_scalar(value)
    return fields, "\n".join(lines[end + 1:])


def as_list(value):
    if value is None or value == "":
        return []
    if isinstance(value, list):
        return value
    return [value]


def link_target(link):
    """Turn "[[Raw/Sources/x|X]]" or "Raw/Sources/x.md" into "Raw/Sources/x.md"."""
    target = str(link).strip()
    if target.startswith("[[") and target.endswith("]]"):
        target = target[2:-2]
    target = target.split("|", 1)[0].split("#", 1)[0].strip().replace("\\", "/")
    target = target.lstrip("./")
    if target and not target.lower().endswith(".md"):
        target += ".md"
    return target


def first_paragraph(body, limit=200):
    for block in re.split(r"\n\s*\n", body):
        text = re.sub(r"<!--.*?-->", "", block, flags=re.S).strip()
        if text and not text.startswith("#"):
            text = " ".join(text.split())
            return text if len(text) <= limit else text[: limit - 3].rstrip() + "..."
    return ""


def wiki_notes():
    """Compiled notes: Markdown files inside the Wiki/ subfolders, minus indexes."""
    notes = []
    for folder in WIKI_FOLDERS:
        base = WIKI / folder
        if base.is_dir():
            notes.extend(
                path for path in base.rglob("*.md") if path.name.lower() != "index.md"
            )
    return sorted(notes, key=rel)


def raw_sources():
    if not RAW_SOURCES.is_dir():
        return []
    return sorted(RAW_SOURCES.rglob("*.md"), key=rel)


def load_note(path):
    fields, body = parse_frontmatter(read_text(path))
    return fields, body


def note_record(path):
    fields, body = load_note(path)
    fields = fields or {}
    tags = as_list(fields.get("tags"))
    return {
        "path": rel(path),
        "title": str(fields.get("title") or path.stem),
        "tag": tags[0] if len(tags) == 1 else tags,
        "topics": as_list(fields.get("topics")),
        "sources": as_list(fields.get("sources")),
        "source_count": fields.get("source_count"),
        "status": fields.get("status", ""),
        "aliases": as_list(fields.get("aliases")),
        "updated": str(fields.get("updated", "")),
        "summary": first_paragraph(body),
    }


def coverage_map():
    """Raw source path -> sorted list of Wiki notes that cite it."""
    covered = {}
    for path in wiki_notes():
        fields, _ = load_note(path)
        for link in as_list((fields or {}).get("sources")):
            covered.setdefault(link_target(link), set()).add(rel(path))
    return {source: sorted(notes) for source, notes in covered.items()}


def read_jsonl(path):
    if not path.exists():
        return None
    records = []
    for number, line in enumerate(read_text(path).splitlines(), start=1):
        if line.strip():
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError as error:
                raise SystemExit("ERROR {}:{}: invalid JSON ({})".format(rel(path), number, error))
    return records


def write_jsonl(path, records):
    write_text(path, "".join(json.dumps(record, ensure_ascii=False, sort_keys=True) + "\n" for record in records))


def report(errors, warnings, ok_message):
    for warning in warnings:
        print("WARN  " + warning)
    for error in errors:
        print("ERROR " + error)
    if errors:
        print("FAILED: {} error(s), {} warning(s)".format(len(errors), len(warnings)))
        return 1
    print("OK    " + ok_message + (" ({} warning(s))".format(len(warnings)) if warnings else ""))
    return 0


# ---------------------------------------------------------------- commands


def cmd_doctor(args):
    errors, warnings = [], []
    if sys.version_info < (3, 8):
        errors.append("Python 3.8 or newer is required (found {}.{})".format(*sys.version_info[:2]))
    print("Python   {}.{}.{}".format(*sys.version_info[:3]))
    for folder in REQUIRED_DIRS:
        if not (ROOT / folder).is_dir():
            errors.append("missing folder: " + folder)
    notes, sources = wiki_notes(), raw_sources()
    counts = {folder: 0 for folder in WIKI_FOLDERS}
    for path in notes:
        counts[path.relative_to(WIKI).parts[0]] += 1
    print("Wiki     {} note(s): ".format(len(notes)) + ", ".join("{} {}".format(n, f) for f, n in counts.items()))
    print("Raw      {} source(s) in Raw/Sources".format(len(sources)))
    catalog = read_jsonl(CATALOG)
    if catalog is None:
        warnings.append("Wiki/catalog.jsonl does not exist yet: run `build`")
    elif sorted(r.get("path") for r in catalog) != [rel(p) for p in notes]:
        warnings.append("Wiki/catalog.jsonl is out of date: run `build`")
    else:
        print("Catalog  {} entr(y/ies), up to date".format(len(catalog)))
    if not INDEX.exists():
        warnings.append("Wiki/index.md does not exist yet: run `build`")
    manifest = read_jsonl(MANIFEST)
    if manifest is None:
        warnings.append("Schema/source-manifest.jsonl does not exist yet: run `source-scan --update`")
    elif sorted(r.get("path") for r in manifest) != [rel(p) for p in sources]:
        warnings.append("Schema/source-manifest.jsonl is out of date: run `source-scan --update`")
    else:
        print("Manifest {} entr(y/ies), up to date".format(len(manifest)))
    return report(errors, warnings, "doctor: vault structure looks healthy")


def render_index(title, records):
    lines = ["# " + title, "", GENERATED_NOTICE, ""]
    if not records:
        lines.append("No notes yet.")
    for record in records:
        target = record["path"][: -len(".md")]
        line = "- [[{}|{}]]".format(target, record["title"])
        if record["summary"]:
            line += ": " + record["summary"]
        lines.append(line)
    return "\n".join(lines) + "\n"


def cmd_build(args):
    records = [note_record(path) for path in wiki_notes()]
    write_jsonl(CATALOG, records)
    sections = ["# Wiki Index", "", GENERATED_NOTICE, ""]
    sections.append("{} compiled note(s).".format(len(records)))
    for folder in WIKI_FOLDERS:
        in_folder = [r for r in records if r["path"].startswith("Wiki/{}/".format(folder))]
        write_text(WIKI / folder / "index.md", render_index(folder, in_folder))
        sections += ["", "## [[Wiki/{}/index|{}]] ({})".format(folder, folder, len(in_folder)), ""]
        if not in_folder:
            sections.append("No notes yet.")
        for record in in_folder:
            sections.append("- [[{}|{}]]".format(record["path"][: -len(".md")], record["title"]))
    write_text(INDEX, "\n".join(sections) + "\n")
    print("OK    build: wrote Wiki/catalog.jsonl ({} note(s)), Wiki/index.md and {} folder indexes".format(
        len(records), len(WIKI_FOLDERS)))
    return 0


def cmd_lint(args):
    errors, warnings = [], []
    notes = wiki_notes()
    for path in notes:
        where = rel(path)
        fields, _ = load_note(path)
        if fields is None:
            errors.append(where + ": no frontmatter (the --- block at the top)")
            continue
        for key in WIKI_REQUIRED:
            if key not in fields:
                errors.append("{}: missing `{}`".format(where, key))
        tags = as_list(fields.get("tags"))
        folder_tag = WIKI_FOLDERS[path.relative_to(WIKI).parts[0]]
        if len(tags) != 1 or tags[0] not in ALLOWED_TAGS:
            errors.append("{}: `tags` must be exactly one of {} (found {})".format(
                where, ", ".join(sorted(ALLOWED_TAGS)), tags))
        elif tags[0] != folder_tag:
            errors.append("{}: tag `{}` does not match its folder (expected `{}`)".format(where, tags[0], folder_tag))
        status = fields.get("status")
        if "status" in fields and status not in ALLOWED_STATUS:
            errors.append("{}: `status` must be one of {} (found {!r})".format(
                where, ", ".join(sorted(ALLOWED_STATUS)), status))
        for key in ("created", "updated"):
            if key in fields and not DATE_RE.match(str(fields[key])):
                errors.append("{}: `{}` must be a date like 2026-01-31 (found {!r})".format(where, key, fields[key]))
        sources = as_list(fields.get("sources"))
        if "sources" in fields and not sources:
            errors.append(where + ": `sources` is empty; link at least one file in Raw/Sources/")
        count = fields.get("source_count")
        if "source_count" in fields and count != len(sources):
            errors.append("{}: `source_count` is {!r} but `sources` has {}".format(where, count, len(sources)))
        for link in sources:
            target = link_target(link)
            if not target.startswith("Raw/Sources/"):
                errors.append("{}: source {!r} is not under Raw/Sources/".format(where, link))
            elif not (ROOT / target).is_file():
                errors.append("{}: source {!r} points to a missing file ({})".format(where, link, target))
    return report(errors, warnings, "lint: {} compiled note(s) checked".format(len(notes)))


def scan_sources(accept_covered):
    covered = coverage_map()
    entries = []
    for path in raw_sources():
        fields, _ = load_note(path)
        fields = fields or {}
        covered_by = covered.get(rel(path), [])
        processed = fields.get("Processed") is True or (accept_covered and bool(covered_by))
        entries.append({
            "path": rel(path),
            "title": str(fields.get("Title") or path.stem),
            "processed": processed,
            "covered_by": covered_by,
        })
    return entries


def cmd_source_scan(args):
    entries = scan_sources(args.accept_covered)
    if not entries:
        print("No sources in Raw/Sources yet.")
    for entry in entries:
        print("{:<5} {}  (covered by {} note(s))".format(
            "done" if entry["processed"] else "todo", entry["path"], len(entry["covered_by"])))
    if args.update:
        previous = {r.get("path"): r for r in (read_jsonl(MANIFEST) or [])}
        records = []
        for entry in entries:
            old = previous.get(entry["path"])
            unchanged = old and all(old.get(k) == entry[k] for k in entry)
            entry["updated"] = old.get("updated", today()) if unchanged else today()
            records.append(entry)
        write_jsonl(MANIFEST, records)
        print("OK    source-scan: wrote Schema/source-manifest.jsonl ({} source(s))".format(len(records)))
    elif args.accept_covered:
        print("Note: --accept-covered only changes the manifest together with --update.")
    return 0


def cmd_source_lint(args):
    errors, warnings = [], []
    covered = coverage_map()
    sources = raw_sources()
    for path in sources:
        where = rel(path)
        fields, _ = load_note(path)
        if fields is None:
            errors.append(where + ": no frontmatter (the --- block at the top)")
            continue
        for key in SOURCE_REQUIRED:
            if key not in fields or fields[key] == "":
                errors.append("{}: missing `{}`".format(where, key))
        if "Processed" in fields and not isinstance(fields["Processed"], bool):
            errors.append("{}: `Processed` must be true or false (found {!r})".format(where, fields["Processed"]))
        if "tags" in fields and "source" not in as_list(fields["tags"]):
            errors.append(where + ": `tags` must include `source`")
        if "Created" in fields and fields["Created"] != "" and not DATE_RE.match(str(fields["Created"])):
            errors.append("{}: `Created` must be a date like 2026-01-31 (found {!r})".format(where, fields["Created"]))
        if fields.get("Processed") is True and not covered.get(where):
            errors.append(where + ": marked Processed but no Wiki note lists it in `sources`")
        if fields.get("Processed") is False and covered.get(where):
            warnings.append(where + ": covered by Wiki notes but still `Processed: false`")
    manifest = read_jsonl(MANIFEST)
    if manifest is not None:
        for record in manifest:
            path = record.get("path", "")
            if record.get("processed") and not covered.get(path):
                errors.append("Schema/source-manifest.jsonl: {} is marked processed but has no Wiki coverage".format(path))
        if sorted(r.get("path") for r in manifest) != [rel(p) for p in sources]:
            warnings.append("Schema/source-manifest.jsonl is out of date: run `source-scan --update`")
    elif sources:
        warnings.append("Schema/source-manifest.jsonl does not exist yet: run `source-scan --update`")
    for target in sorted(covered):
        if target.startswith("Raw/Sources/") and not (ROOT / target).is_file():
            warnings.append("{} is cited by {} but does not exist".format(target, ", ".join(covered[target])))
    return report(errors, warnings, "source-lint: {} source(s) checked".format(len(sources)))


def cmd_source_delta(args):
    manifest = read_jsonl(MANIFEST)
    known = {r.get("path"): r for r in (manifest or [])}
    current = {entry["path"]: entry for entry in scan_sources(False)}
    new = [path for path in current if path not in known]
    gone = [path for path in known if path not in current]
    if manifest is None:
        print("Schema/source-manifest.jsonl does not exist yet, so every source is new.")
    for path in new:
        print("new      " + path)
    for path in gone:
        print("removed  " + path)
    print("OK    source-delta: {} new, {} removed".format(len(new), len(gone)))
    return 0


def cmd_source_coverage(args):
    entries = scan_sources(False)
    if not entries:
        print("No sources in Raw/Sources yet.")
    for entry in entries:
        print(entry["path"])
        for note in entry["covered_by"] or ["(not covered by any Wiki note yet)"]:
            print("    " + note)
    covered = sum(1 for entry in entries if entry["covered_by"])
    print("OK    source-coverage: {} of {} source(s) covered".format(covered, len(entries)))
    return 0


def cmd_search_catalog(args):
    catalog = read_jsonl(CATALOG)
    if catalog is None:
        print("ERROR Wiki/catalog.jsonl does not exist yet: run `build` first")
        return 1
    terms = [term for term in re.split(r"\W+", args.query.lower()) if term]
    if not terms:
        print("ERROR give some words to search for, e.g. --query \"llm wiki\"")
        return 2
    results = []
    for record in catalog:
        title = str(record.get("title", "")).lower()
        meta = " ".join(str(v) for v in [record.get("path", "")] + as_list(record.get("topics"))
                        + as_list(record.get("aliases")) + as_list(record.get("tag"))).lower()
        summary = str(record.get("summary", "")).lower()
        score = sum(3 * (term in title) + 2 * (term in meta) + (term in summary) for term in terms)
        if score:
            results.append((-score, record.get("path", ""), record))
    results.sort(key=lambda item: (item[0], item[1]))
    for negative_score, _, record in results[: args.limit]:
        print("{:>3}  {}  [{}]".format(-negative_score, record.get("path"), record.get("tag")))
        if record.get("summary"):
            print("     " + record["summary"])
    print("OK    search-catalog: {} match(es) for {!r}".format(len(results), args.query))
    return 0


def cmd_log(args):
    title = " ".join(args.title.split())
    details = " ".join(args.details.split())
    if not title:
        print("ERROR --title cannot be empty")
        return 2
    existing = read_text(LOG) if LOG.exists() else "# Wiki Log\n\nOne line per meaningful change, newest at the bottom.\n\n"
    if not existing.endswith("\n"):
        existing += "\n"
    entry = "- {} **{}**".format(today(), title) + (": " + details if details else "") + "\n"
    write_text(LOG, existing + entry)
    print("OK    log: added to Wiki/log.md: " + entry.strip())
    return 0


def main(argv=None):
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass
    parser = argparse.ArgumentParser(
        prog="wiki_tool.py",
        description="Build, check and search the LLM Wiki. See Schema/command-reference.md.")
    sub = parser.add_subparsers(dest="command", metavar="command")
    sub.required = True
    sub.add_parser("doctor", help="read-only health check of folders, Python, catalog and manifest")
    sub.add_parser("build", help="write Wiki/catalog.jsonl, Wiki/index.md and per-folder indexes")
    sub.add_parser("lint", help="check compiled Wiki notes")
    scan = sub.add_parser("source-scan", help="list Raw sources; --update writes the source manifest")
    scan.add_argument("--update", action="store_true", help="write Schema/source-manifest.jsonl")
    scan.add_argument("--accept-covered", action="store_true",
                      help="count sources cited by Wiki notes as processed in the manifest")
    sub.add_parser("source-lint", help="check Raw source frontmatter and coverage")
    sub.add_parser("source-delta", help="show Raw sources missing from (or gone from) the manifest")
    sub.add_parser("source-coverage", help="show which Wiki notes cite each Raw source")
    search = sub.add_parser("search-catalog", help="search compiled notes through the catalog")
    search.add_argument("--query", required=True, help="words to look for")
    search.add_argument("--limit", type=int, default=10, help="most results to show (default 10)")
    log = sub.add_parser("log", help="append a line to Wiki/log.md")
    log.add_argument("--title", required=True)
    log.add_argument("--details", default="")
    args = parser.parse_args(argv)
    handler = {
        "doctor": cmd_doctor,
        "build": cmd_build,
        "lint": cmd_lint,
        "source-scan": cmd_source_scan,
        "source-lint": cmd_source_lint,
        "source-delta": cmd_source_delta,
        "source-coverage": cmd_source_coverage,
        "search-catalog": cmd_search_catalog,
        "log": cmd_log,
    }[args.command]
    return handler(args)


if __name__ == "__main__":
    sys.exit(main())
